// <auto-generated />
namespace MVC_Homework_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ButtonChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ButtonChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201707210829579_Button-Changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
