//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApp
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    public partial class SalesDatabaseEntities1 : DbContext
    {
        public SalesDatabaseEntities1() : base("name=SalesDatabaseEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // throw new UnintentionalCodeFirstException();

            base.OnModelCreating(modelBuilder);
            modelBuilder.Conventions.Remove<System.Data.Entity.ModelConfiguration.Conventions.PluralizingTableNameConvention>();

        }


        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<StoreLocation> StoreLocations { get; set; }


        public class CustomerDbInitializer : DropCreateDatabaseIfModelChanges<SalesDatabaseEntities1>
        {
            protected override void Seed(SalesDatabaseEntities1 context)
            {
                var customers = new List<Customer>
            {
                new Customer {  Id = 1, Name = "Ionesccu Andrei", Email = "ionescu@gmail.com", CreditCardNumber = "2134567865"  },
                new Customer { Id = 2, Name = "Henry Roy", Email = "henry@gmail.com", CreditCardNumber = "2389067865" },
                new Customer { Id = 3, Name = "Lucian Anderson", Email = "anderson.l@gmail.com", CreditCardNumber = "2100007865" },
                new Customer { Id = 4, Name = "Georgescu Popescu", Email = "popescu@gmail.com", CreditCardNumber = "2345997865"},

            };
                customers.ForEach(s => context.Customers.Add(s));
                context.SaveChanges();
            }
        }

        }

    }



